# Generated by Django 4.2.1 on 2023-10-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.reader')),
            ],
            options={
                'db_table': 'reader_counts',
                'managed': True,
            },
        ),
    ]
