# Generated by Django 4.2.1 on 2023-10-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_readercounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readercounter',
            options={'managed': False},
        ),
    ]
