# Generated by Django 4.0.4 on 2022-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconreaders',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beaconreaders',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='beacontags',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
