# Generated by Django 4.0.4 on 2022-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_beaconreaders_name_alter_beaconreaders_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedBeaconTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_uid', models.CharField(max_length=200)),
                ('tag_uid', models.CharField(max_length=200)),
                ('rssi', models.CharField(max_length=200)),
                ('read_datetime', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
