# Generated by Django 4.0.4 on 2022-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_loadedbeacontags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwReadtags',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=200)),
                ('rssi', models.CharField(max_length=200)),
                ('read_datetime', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'vw_readtags',
                'managed': False,
            },
        ),
    ]
