# Generated by Django 4.0.4 on 2022-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_beaconreaders_active_beacontags_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacontags',
            name='last_rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
