# Generated by Django 4.0.4 on 2022-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_beacontags_last_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacontags',
            name='last_read',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
