# Generated by Django 4.0.4 on 2022-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_beacontags_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacontags',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
