# Generated by Django 4.0.4 on 2022-09-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_beacontags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacontags',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
