# Generated by Django 4.0.4 on 2022-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_beacontags_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beacontags',
            options={'ordering': ('-last_rssi',)},
        ),
        migrations.AddField(
            model_name='beacontags',
            name='UUIDs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beacontags',
            name='local_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
