# Generated by Django 4.0.4 on 2022-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_beacontags_options_beacontags_uuids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconreaders',
            name='is_setting_reader',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='beaconreaders',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='loadedbeacontags',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
