# Generated by Django 4.0.4 on 2022-10-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_vwtagslastrssi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vwtagslastrssi',
            options={'managed': False, 'ordering': ('last_rssi', 'uid')},
        ),
    ]
